#Stage 1: Build
FROM maven:4.0.0-eclipse-temurin-25 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

#Stage 2: Run
FROM eclipse-temurin:25-jdk
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
ENTRYPOINT [ "java", "-jar", "app.jar" ]

